FROM debian:buster

RUN apt update && apt upgrade && apt-get install -y gnupg2 wget lsb-release 
RUN wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add -

RUN echo "deb http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" > /etc/apt/sources.list.d/freeswitch.list
RUN echo "deb-src http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" >> /etc/apt/sources.list.d/freeswitch.list

RUN apt update

RUN apt install -y freeswitch freeswitch-conf-curl freeswitch-conf-insideout freeswitch-conf-sbc freeswitch-conf-softphone freeswitch-lang freeswitch-lang-en freeswitch-lang-ru freeswitch-mod-abstraction freeswitch-mod-amr freeswitch-mod-amrwb freeswitch-mod-av freeswitch-mod-avmd freeswitch-mod-b64 freeswitch-mod-blacklist freeswitch-mod-bv freeswitch-mod-callcenter freeswitch-mod-cdr-csv freeswitch-mod-cdr-mongodb freeswitch-mod-cdr-sqlite freeswitch-mod-cidlookup freeswitch-mod-codec2 freeswitch-mod-commands freeswitch-mod-conference freeswitch-mod-console freeswitch-mod-curl freeswitch-mod-dahdi-codec freeswitch-mod-db freeswitch-mod-dialplan-asterisk freeswitch-mod-dialplan-directory freeswitch-mod-dialplan-xml freeswitch-mod-dingaling freeswitch-mod-directory freeswitch-mod-distributor freeswitch-mod-dptools freeswitch-mod-easyroute freeswitch-mod-enum freeswitch-mod-erlang-event freeswitch-mod-esf freeswitch-mod-esl freeswitch-mod-event-multicast freeswitch-mod-event-socket freeswitch-mod-expr freeswitch-mod-fifo freeswitch-mod-flite freeswitch-mod-fsk freeswitch-mod-fsv freeswitch-mod-g723-1 freeswitch-mod-g729 freeswitch-mod-h26x freeswitch-mod-hash freeswitch-mod-httapi freeswitch-mod-http-cache freeswitch-mod-isac freeswitch-mod-json-cdr freeswitch-mod-lcr freeswitch-mod-local-stream freeswitch-mod-logfile freeswitch-mod-loopback freeswitch-mod-lua freeswitch-mod-mp4v freeswitch-mod-native-file freeswitch-mod-opus freeswitch-mod-oreka freeswitch-mod-perl freeswitch-mod-pgsql freeswitch-mod-png freeswitch-mod-pocketsphinx freeswitch-mod-portaudio freeswitch-mod-portaudio-stream freeswitch-mod-posix-timer freeswitch-mod-python freeswitch-mod-redis freeswitch-mod-hiredis freeswitch-mod-rss freeswitch-mod-rtc freeswitch-mod-rtmp freeswitch-mod-say-en freeswitch-mod-say-ru freeswitch-mod-shell-stream freeswitch-mod-shout freeswitch-mod-silk freeswitch-mod-skinny freeswitch-mod-sms freeswitch-mod-snapshot freeswitch-mod-sndfile freeswitch-mod-snmp freeswitch-mod-snom freeswitch-mod-sofia freeswitch-mod-sonar freeswitch-mod-soundtouch freeswitch-mod-spandsp freeswitch-mod-spy freeswitch-mod-stress freeswitch-mod-syslog freeswitch-mod-theora freeswitch-mod-timerfd freeswitch-mod-tone-stream freeswitch-mod-translate freeswitch-mod-tts-commandline freeswitch-mod-valet-parking freeswitch-mod-video-filter freeswitch-mod-voicemail freeswitch-mod-voicemail-ivr freeswitch-mod-xml-cdr freeswitch-mod-xml-curl freeswitch-mod-xml-rpc freeswitch-mod-xml-scgi freeswitch-mod-yaml freeswitch-music-default freeswitch-sounds-en-us-callie freeswitch-sounds-ru-ru-vika freeswitch-timezones libfreeswitch1

CMD freeswitch 
