version: '3'

services:
        redis:
                image: redis

        db:
                image: postgres
                ports:
                        - "5432:5432"
                environment:
                        - POSTGRES_DB=asterconf_fs
                        - POSTGRES_USER=asterconf_fs
                        - POSTGRES_PASSWORD=asterconf_fs

        migrate:
                image: lehalepeha/asterconf_web
                command: python manage.py migrate
                depends_on:
                        - db

        web:
                image: lehalepeha/asterconf_web
                command: python manage.py runserver 0.0.0.0:8000
                ports:
                        - "8000:8000"
                depends_on:
                        - migrate               

        freeswitch:
                image: lehalepeha/asterconf_fs
                command: freeswitch
                volumes:
                        - ./freeswitch:/etc/freeswitch
                        - ./scripts:/usr/share/freeswitch/scripts
                depends_on:
                        - web
